import sys

from elftools.elf.elffile import ELFFile
from elftools.elf.sections import SymbolTableSection


def get_symbols(elf_path: str):
    with open(elf_path, "rb") as f:
        elf = ELFFile(f)

        section = elf.get_section_by_name(".symtab")

        if not isinstance(section, SymbolTableSection):
            raise RuntimeError(".symtab not found")

        symbols = []

        for sym in section.iter_symbols():
            info = sym["st_info"]

            if info["type"] != "STT_FUNC":
                continue

            addr = sym["st_value"]
            size = sym["st_size"]
            name = sym.name

            if not name:
                continue

            symbols.append((addr, size, name))

    symbols.sort(key=lambda x: x[0])

    return symbols


def generate_c(symbols):
    strings = bytearray()
    name_offsets = {}

    for _, _, name in symbols:
        if name in name_offsets:
            continue

        name_offsets[name] = len(strings)
        strings.extend(name.encode("ascii"))
        strings.append(0)

    out = []

    out.append("/* generated by tools/ksymbols.py */")
    out.append("")
    out.append("#include <serika/symbol.h>")
    out.append("")

    out.append("const struct ksymbol ksymbols[] = {")

    for addr, size, name in symbols:
        offset = name_offsets[name]

        out.append(
            f"    {{ .addr = 0x{addr:x}, "
            f".size = {size}, "
            f".name_offset = {offset} }},"
        )

    out.append("};")
    out.append("")

    out.append(
        "const size_t ksymbol_count = "
        "sizeof(ksymbols) / sizeof(ksymbols[0]);"
    )
    out.append("")

    out.append("const char ksymbol_names[] =")

    offset = 0
    while offset < len(strings):
        end = strings.index(0, offset)
        name = strings[offset:end].decode("ascii")

        out.append(f'    "{name}\\0"')

        offset = end + 1

    out[-1] += ";"
    out.append("")

    return "\n".join(out)

def generate_stub():
    return """/* generated by tools/ksymbols.py --stub */

#include <stddef.h>
#include <stdint.h>

#include <serika/symbol.h>

const struct ksymbol ksymbols[] = {};
const size_t ksymbol_count = 0;
const char ksymbol_names[] = "";
"""

def main():
    if len(sys.argv) == 3 and sys.argv[1] == "--stub":
        with open(sys.argv[2], "w", encoding="UTF-8") as f:
            f.write(generate_stub())

        return 0

    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <elf> <output>")
        print(f"       {sys.argv[0]} --stub <output>")
        return 1

    elf_path = sys.argv[1]
    output_path = sys.argv[2]

    symbols = get_symbols(elf_path)

    with open(output_path, "w", encoding="UTF-8") as f:
        f.write(generate_c(symbols))

    print(f"{len(symbols)} symbols")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
